from preprocessing.config import PATH_SMAP_FOLDER, BOUNDING_BOX, SMAP_FEATURES_NAMES, PATH_CYGNSS_FOLDER, \
    PATH_WATER_MAP_FILE, CYNGNSS_FEATURES_NAMES, PATH_LAND_COVER_MAP_FILE, PATH_TRAIN_WITH_LABEL_FOLDER, \
    PATH_TRAIN_WITHOUT_LABEL_FOLDER
from preprocessing.smap import main

if __name__ == '__main__':
    main(PATH_SMAP_FOLDER, BOUNDING_BOX, SMAP_FEATURES_NAMES)
    main(PATH_CYGNSS_FOLDER, PATH_WATER_MAP_FILE, BOUNDING_BOX, CYNGNSS_FEATURES_NAMES, PATH_LAND_COVER_MAP_FILE,
         PATH_SMAP_FOLDER, PATH_TRAIN_WITH_LABEL_FOLDER, PATH_TRAIN_WITHOUT_LABEL_FOLDER),